#version: '3.9'

services:
  my_host:

    build:
      context: .
      dockerfile: Dockerfile
    #image: anding/infrabuilding:v3
    stdin_open: true
    tty: true
    container_name: host_tbx

    volumes:
      - C:\Users\Andin\PycharmProjects\AUTO-PENTESTING\Reports:/usr/share/sniper/loot/workspace/
      - C:\Users\Andin\PycharmProjects\AUTO-PENTESTING:/app/projet-M1
    networks:
      - my_network

    command: "/bin/bash"

  vulnhost:
    image: tleemcjr/metasploitable2:latest
    stdin_open: true
    tty: true
    container_name: vuln-cont
    networks:
      - my_network

  GUI-vuln-scan:
    image: anding/vulnscan:v1
    container_name: gui-vuln-scan
    ports:
      - "443:443"   # Expose OPenVAS Web
      - "9390:9390" # Expose OpenVAS Manager
    volumes:
      - C:\Users\Andin\PycharmProjects\AUTO-PENTESTING\ovas-volume:/app/TBX_volume
    networks:
      - my_network
    environment:
      - OV_UPDATE_TOOLS=true
      - OV_PASSWORD=adgsupdevincitbx
    restart: unless-stopped

    labels:
      deck-chores.dump.command: sh -c "greenbone-nvt-sync; openvasmd --rebuild --progress"
      deck-chores.dump.interval: daily

networks:
  my_network:
    name: network_Vianney
    driver: bridge

